cart/urls.py
from django.conf.urls import url
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    )

urlpatterns = [    
    url(r'^$',cart_home,name='cart_home'),
    url(r'^update/$',cart_update,name='update'), 
    url(r'^checkout/$', checkout_home ,name='checkout')   
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url , include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from accounts.views import login_page,register_page
from .views import home ,contact

urlpatterns = [
    url(r'^$',home ,name='home'),
    url(r'^contact/$' ,contact,name='contact'),
    url(r'^login/$' ,login_page,name='login'),
    url(r'^logout/$' ,LogoutView.as_view() ,name='logout'),
    url(r'^register/$' ,register_page,name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'^products/',include("products.urls")),
    url(r'^search/',include("search.urls")),
    url(r'^cart/',include("cart.urls", namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.conf import settings
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save, post_save,m2m_changed

# Create your models here.

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
    
        qs = self.get_queryset().filter(id=cart_id) 
        if qs.count()==1: 
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None: #if created without logging in then assigning auth user to that cart
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj =Cart.objects.new(user= request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id 
        return cart_obj ,new_obj     


    def new(self, user= None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj= user
        return self.model.objects.create(user=user_obj)



class Cart(models.Model):
    user =  models.ForeignKey(User, null=True , blank= True) # so that any user can create a cart 
    products = models.ManyToManyField(Product , blank= True) # so that cart can be blank as well
    sub_total = models.DecimalField(default=0.00, max_digits=50,decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=50,decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models. DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender , instance , action, *args , **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post__clear':
        products = instance.products.all()
        sub_total = 0
        for x in products:
            sub_total += x.price 
        instance.sub_total = sub_total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through) #Model.m2mfield.through


def pre_save_cart_receiver(sender , instance , *args , **kwargs):
    if instance.sub_total > 0:
        instance.total = float(instance.sub_total) * 1.13 # adding taxes
    else:
        instance.total =0.00

pre_save.connect(pre_save_cart_receiver,sender=Cart)

    

cart/views.py
from django.shortcuts import render ,redirect

from accounts.forms import LoginForm
from billing.models import BillingProfile
from products.models import Product
from orders.models import Order

from .models import Cart

# Create your views here.

def cart_home(request):
    # del request.session['cart_id'] 
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request,"carts/home.html",{"cart":cart_obj})

def cart_update(request):  
    product_id = request.POST.get('product_id')
    print (request.POST)
    print(product_id) 
    if product_id is not None:
        try:           
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("error message")
            return redirect("cart:cart_home")            
        cart_obj ,new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items']=cart_obj.products.count() # to return number of items in cart

    return redirect("cart:cart_home")

def checkout_home(request):
    cart_obj , cart_created = Cart.objects.new_or_get(request)
    
    if cart_created or cart_obj.products.count() ==0: # if not creatd new or products is empty
        return redirect("cart:cart_home")
    else:        
        order_obj , obj_created = Order.objects.get_or_create(cart=cart_obj)
    user = request.user

    billing_profile = None
    login_form = LoginForm()
    if user.is_authenticated():
        billing_profile , billing_profile_created = BillingProfile.objects.get_or_create(user=user , email=user.email)
    context={
        "object":order_obj,
        "billing_profile":billing_profile,
        "login_form":login_form

    }

    return render (request , "carts/checkout.html",context)


    

cart/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}

{% if not billing_profile %}
<div class="row ">

    <div class="col-md-6 text-center">

    Login 
    {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    <div class="col-md-6">
    Continue as Guest
    </div>
</div>
{% else %}
    <h1>Checkout</h1> 

    <p> Cart Total: {{ object.cart.total }} </p>
    <p>Shipping Total: {{ object.shipping_total }}  </p>
    <p> Order Total : {{ object.total}} </p>
{% endif %}
{% endblock %} 

cart/templates/carts/home.html
{% extends "base.html" %}

{% block content %}

<style>
        #total{
            text-align: right;
        }
        
</style>

<h1> Cart </h1>
{% if cart.products.exists%}
<table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>            
          </tr>
        </thead>
        <tbody>
            {% for product in cart.products.all %}
          <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td> <a href="{{product.get_absolute_url }}" >{{ product.title }}</a> 
                {% include 'snippets/update_cart.html' with in_cart=True%}  
                 
            </td>
            <td>{{ product.price }}</td>            
          </tr>
          {% endfor %}
          <tr>           
            <td></td>
            <td id="total" ><b> Subtotal </b> </td>
            <td >{{ cart.sub_total }}</td>
          </tr>
          <tr>
            <td></td>
            <td id="total" ><b>  Total </b> </td>
            <td> {{ cart.total }}</td>
          </tr>
          <tr>
              <td colspan="2"></td>              
              <td> <a class='btn btn-success' href="{% url 'cart:checkout' %}">Checkout </a></td>
            </tr>
        </tbody>
      </table>
    {% else %}

    <h1> empty </h1>
    {% endif %}

{% endblock %}