cart/urls.py
from django.conf.urls import url
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    )

urlpatterns = [    
    url(r'^$',cart_home,name='cart_home'),
    url(r'^update/$',cart_update,name='update'), 
    url(r'^checkout/$', checkout_home ,name='checkout')   
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url , include
from django.contrib import admin
from django.contrib.auth.views import LogoutView

from accounts.views import login_page,register_page
from .views import home ,contact

urlpatterns = [
    url(r'^$',home ,name='home'),
    url(r'^contact/$' ,contact,name='contact'),
    url(r'^login/$' ,login_page,name='login'),
    url(r'^logout/$' ,LogoutView.as_view() ,name='logout'),
    url(r'^register/$' ,register_page,name='register'),
    url(r'^admin/', admin.site.urls),
    url(r'^products/',include("products.urls")),
    url(r'^search/',include("search.urls")),
    url(r'^cart/',include("cart.urls", namespace='cart')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">     
           </head>
        <body>
            {% include "navbar.html" %}
            <div class="container">
                {%block content %}

                {% endblock %}
             </div>  

            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
          

        </body>
        
    </html>

templates/contact.html
{% extends "base.html"%}

{% block content %}
<div class='row'>
    <div class="col-sm-6">
        Welcome to {{title}}
        <form method="POST">{% csrf_token %} <br>

         {{form.as_p}}
        <button type="submit" >Submit</button>
          

        </form>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}

    {% block content %}
    <p>{{title}}</p>

    {% if request.user.is_authenticated %}

    <h3>Premium</h3>
    <p>{{premium_content}}</p>
    {% endif %}
    
    {% endblock %}

templates/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'list' as product_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'cart:cart_home' as cart_url %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="#">E-commerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.path == home_url %} active {% endif %}">
              <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.path == contact_url %} active {% endif %}">
              <a class="nav-link" href="{{ contact_url }}">Contact</a>
            </li>

            <li class="nav-item {% if request.path == product_url %} active {% endif %}">
                    <a class="nav-link" href="{{ product_url }}">Products</a>
            </li>

            <li class="nav-item {% if request.path == cart_url %} active {% endif %}">                
                <a class="nav-link" href="{{ cart_url }}"> <i class="fa fa-shopping-cart" aria-hidden="true"></i><sup> {{ request.session.cart_items}} </sup></a>
            </li>
            <!-- <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li> -->
            
          </ul>

          <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
              <li class="nav-item {% if request.path == logout_url %} active {% endif %}">
                  <a class="nav-link" href="{{ logout_url }}">Logout</a>
              </li>
              {% else %}
  
              <li class="nav-item {% if request.path == register_url %} active {% endif %}">
                      <a class="nav-link" href="{{ register_url }}">Register</a>
              </li>
  
              <li class="nav-item {% if request.path == login_url %} active {% endif %}">
                      <a class="nav-link" href="{{ login_url }}">Login</a>
              </li>
  
              {% endif %}
              
            </ul>

          <form method="GET" action="{% url 'search'%}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" name='q' aria-label="Search" value="{{query}}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          
          
          
        </div>
      </nav>